### ISSUE TITLE
Error when there are more than 100 labels in the model

### ISSUE THREAD

**Issue by oneprofittips** [NickSwardh/YoloDotNet#6]
Unhandled exception. System.Exception: There are more labels than available colors.
   at YoloDotNet.Extensions.OnnxPropertiesExtension.MapLabelsAndColors(String onnxLabelData, ModelType modelType)
   at YoloDotNet.Extensions.OnnxPropertiesExtension.GetOnnxProperties(InferenceSession session)
   at YoloDotNet.Data.YoloBase..ctor(String onnxModel, Boolean useCuda, Int32 gpuId)
   at YoloDotNet.Yolo..ctor(String onnxModel, Boolean cuda, Int32 gpuId)

**Comment by NickSwardh** [comment]
Thank you for reaching out. I'll have a look at this.

**Comment by NickSwardh** [comment]
Issue resolved in new version.
